Algoritmo "Ativ.06 Circulo facatVisualG"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : nesse algoritmo iremos ver o calculo da area de um retangulo
// Autor(a)    : Adrielle Merces
// Data atual  : 29/08/2024
Var
base, lado, area:inteiro


Inicio
escreval("digite o valor da base")
leia(base)
escreval("digite o valor do lado")
leia(lado)
area <- base*lado
escreva("Resultado da area do retangulo :", area)

Fimalgoritmo