Algoritmo "Ativ.06 triangulo facatVisualG"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Este algoritmo calcula a area e um triangulo
// Autor(a)    : Adrielle Merces
// Data atual  : 29/08/2024
Var
base, lado, area:inteiro


Inicio
escreval("Digite o valor da base")
leia(base)
escreval("Digite o valor do lado")
leia(lado)
area <- base*lado
escreval("O resultado da area e:", area)


Fimalgoritmo