Algoritmo "ATIV.05 sucessor FacatVisualG"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Jailson
// Descrição   : Neste algoritmo veremos sobre como fazer aparecer o
//numero antessesor do numero que o usuario inserir
// Autor(a)    : Adrielle Merces
// Data atual  : 29/08/2024
Var
numero1:inteiro
resultado:inteiro
Inicio
  escreva("digite um numero")
  leia(numero1)
  resultado <- numero1 -1
  escreva("Resultado", resultado)


Fimalgoritmo